[package]
name = "binvia-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dirs.workspace = true
uuid.workspace = true
chrono.workspace = true
rust-embed.workspace = true
tower-http.workspace = true
tower.workspace = true
reqwest.workspace = true
bytes.workspace = true
mime_guess.workspace = true
base64.workspace = true
