import Foundation

/// Cursor 官方模型目录（静态兜底）。
///
/// 模型 ID 直接同步 OmniRoute `open-sse/config/providers/registry/cursor/index.ts`
/// （2026-05 快照，123 个模型）。这些是 Cursor 内部真实模型 ID（`auto` / `composer-*` /
/// 各厂商 effort 变体），与 IDE 私有协议 `model_details.model_name` 一一对应。
///
/// 注意：`auto` 与 `composer-*` 由 Cursor 服务端/Composer 端点解析，当前 Binvia 用的
/// `StreamUnifiedChatWithTools` 私有端点会拒绝这两个模型（参考 OmniRoute cursor.ts 头注释：
/// 该 executor 已迁移到 `agent.v1.AgentService/Run` 以支持它们）。升级 RPC 前它们仅可展示，
/// 调用会失败。目录结构保持 OmniRoute 顺序：auto / composer / gpt / claude / gemini / grok / kimi。
public enum CursorModels {
    public static let all: [Model] = [
        Model(id: "auto", name: "Auto (Server Picks)", contextLength: 200_000, supportsReasoning: true),
        Model(id: "composer-2.5-fast", name: "Composer 2.5 Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "composer-2.5", name: "Composer 2.5", contextLength: 200_000, supportsReasoning: true),
        Model(id: "composer-2-fast", name: "Composer 2 Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "composer-2", name: "Composer 2", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-none", name: "GPT 5.5 None", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-none-fast", name: "GPT 5.5 None Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-low", name: "GPT 5.5 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-low-fast", name: "GPT 5.5 Low Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-medium", name: "GPT 5.5 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-medium-fast", name: "GPT 5.5 Medium Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-high", name: "GPT 5.5 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-high-fast", name: "GPT 5.5 High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-extra-high", name: "GPT 5.5 Extra High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.5-extra-high-fast", name: "GPT 5.5 Extra High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-low", name: "GPT 5.4 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-low-fast", name: "GPT 5.4 Low Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-medium", name: "GPT 5.4 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-medium-fast", name: "GPT 5.4 Medium Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-high", name: "GPT 5.4 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-high-fast", name: "GPT 5.4 High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-xhigh", name: "GPT 5.4 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-xhigh-fast", name: "GPT 5.4 XHigh Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-mini-none", name: "GPT 5.4 Mini None", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-mini-low", name: "GPT 5.4 Mini Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-mini-medium", name: "GPT 5.4 Mini Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-mini-high", name: "GPT 5.4 Mini High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-mini-xhigh", name: "GPT 5.4 Mini XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-nano-none", name: "GPT 5.4 Nano None", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-nano-low", name: "GPT 5.4 Nano Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-nano-medium", name: "GPT 5.4 Nano Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-nano-high", name: "GPT 5.4 Nano High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.4-nano-xhigh", name: "GPT 5.4 Nano XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-spark-preview-low", name: "GPT 5.3 Codex Spark Preview Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-spark-preview", name: "GPT 5.3 Codex Spark Preview", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-spark-preview-high", name: "GPT 5.3 Codex Spark Preview High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-spark-preview-xhigh", name: "GPT 5.3 Codex Spark Preview XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-low", name: "GPT 5.3 Codex Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-low-fast", name: "GPT 5.3 Codex Low Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex", name: "GPT 5.3 Codex", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-fast", name: "GPT 5.3 Codex Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-high", name: "GPT 5.3 Codex High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-high-fast", name: "GPT 5.3 Codex High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-xhigh", name: "GPT 5.3 Codex XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.3-codex-xhigh-fast", name: "GPT 5.3 Codex XHigh Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-low", name: "GPT 5.2 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-low-fast", name: "GPT 5.2 Low Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2", name: "GPT 5.2", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-fast", name: "GPT 5.2 Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-high", name: "GPT 5.2 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-high-fast", name: "GPT 5.2 High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-xhigh", name: "GPT 5.2 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gpt-5.2-xhigh-fast", name: "GPT 5.2 XHigh Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-low", name: "Claude Opus 4.8 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-low-fast", name: "Claude Opus 4.8 Low Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-medium", name: "Claude Opus 4.8 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-medium-fast", name: "Claude Opus 4.8 Medium Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-high", name: "Claude Opus 4.8 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-high-fast", name: "Claude Opus 4.8 High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-xhigh", name: "Claude Opus 4.8 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-xhigh-fast", name: "Claude Opus 4.8 XHigh Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-max", name: "Claude Opus 4.8 Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-max-fast", name: "Claude Opus 4.8 Max Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-low", name: "Claude Opus 4.8 Thinking Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-low-fast", name: "Claude Opus 4.8 Thinking Low Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-medium", name: "Claude Opus 4.8 Thinking Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-medium-fast", name: "Claude Opus 4.8 Thinking Medium Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-high", name: "Claude Opus 4.8 Thinking High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-high-fast", name: "Claude Opus 4.8 Thinking High Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-xhigh", name: "Claude Opus 4.8 Thinking XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-xhigh-fast", name: "Claude Opus 4.8 Thinking XHigh Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-max", name: "Claude Opus 4.8 Thinking Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-8-thinking-max-fast", name: "Claude Opus 4.8 Thinking Max Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-low", name: "Claude Fable 5 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-medium", name: "Claude Fable 5 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-high", name: "Claude Fable 5 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-xhigh", name: "Claude Fable 5 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-max", name: "Claude Fable 5 Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-thinking-low", name: "Claude Fable 5 Thinking Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-thinking-medium", name: "Claude Fable 5 Thinking Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-thinking-high", name: "Claude Fable 5 Thinking High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-thinking-xhigh", name: "Claude Fable 5 Thinking XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-fable-5-thinking-max", name: "Claude Fable 5 Thinking Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-low", name: "Claude Sonnet 5 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-medium", name: "Claude Sonnet 5 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-high", name: "Claude Sonnet 5 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-xhigh", name: "Claude Sonnet 5 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-max", name: "Claude Sonnet 5 Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-thinking-low", name: "Claude Sonnet 5 Thinking Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-thinking-medium", name: "Claude Sonnet 5 Thinking Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-thinking-high", name: "Claude Sonnet 5 Thinking High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-thinking-xhigh", name: "Claude Sonnet 5 Thinking XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-sonnet-5-thinking-max", name: "Claude Sonnet 5 Thinking Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-low", name: "Claude Opus 4.7 Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-medium", name: "Claude Opus 4.7 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-high", name: "Claude Opus 4.7 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-xhigh", name: "Claude Opus 4.7 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-max", name: "Claude Opus 4.7 Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-thinking-low", name: "Claude Opus 4.7 Thinking Low", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-thinking-medium", name: "Claude Opus 4.7 Thinking Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-thinking-high", name: "Claude Opus 4.7 Thinking High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-thinking-xhigh", name: "Claude Opus 4.7 Thinking XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-opus-4-7-thinking-max", name: "Claude Opus 4.7 Thinking Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-opus-high", name: "Claude 4.6 Opus High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-opus-high-thinking", name: "Claude 4.6 Opus High Thinking", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-opus-high-thinking-fast", name: "Claude 4.6 Opus High Thinking Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-opus-max", name: "Claude 4.6 Opus Max", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-opus-max-thinking", name: "Claude 4.6 Opus Max Thinking", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-opus-max-thinking-fast", name: "Claude 4.6 Opus Max Thinking Fast", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-sonnet-medium", name: "Claude 4.6 Sonnet Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.6-sonnet-medium-thinking", name: "Claude 4.6 Sonnet Medium Thinking", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.5-sonnet", name: "Claude 4.5 Sonnet", contextLength: 200_000, supportsReasoning: true),
        Model(id: "claude-4.5-sonnet-thinking", name: "Claude 4.5 Sonnet Thinking", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", contextLength: 200_000, supportsReasoning: true),
        Model(id: "gemini-3-flash", name: "Gemini 3 Flash", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.3", name: "Grok 4.3", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.5-medium", name: "Grok 4.5 Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.5-fast-medium", name: "Grok 4.5 Fast Medium", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.5-high", name: "Grok 4.5 High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.5-fast-high", name: "Grok 4.5 Fast High", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.5-xhigh", name: "Grok 4.5 XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "grok-4.5-fast-xhigh", name: "Grok 4.5 Fast XHigh", contextLength: 200_000, supportsReasoning: true),
        Model(id: "kimi-k2.5", name: "Kimi K2.5", contextLength: 200_000, supportsReasoning: true),
    ]
}
